<script setup>
import {ref,onMounted} from 'vue'; import QRCode from 'qrcode'; import {Head,useForm,router} from '@inertiajs/vue3'; import Layout from '@/Layouts/main.vue';
const accessQr=ref(''); onMounted(async()=>{accessQr.value=await QRCode.toDataURL(route('membership.register'),{width:240,margin:4})});
const p=defineProps({batches:Array,cards:Array,coupons:Array});
const f=useForm({name:'',quantity:100,expires_at:'',coupon_quantities:Object.fromEntries(p.coupons.map(c=>[c.id,1]))}); const generating=ref(false); const error=ref('');
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
async function create(){generating.value=true;error.value='';try{const r=await window.axios.post(route('card-batches.store'),f.data(),{responseType:'blob'});download(r.data,`${f.name||'lote'}-codigos.csv`);router.reload()}catch(e){error.value='No se pudo crear el lote. Verifica la referencia y las cantidades.'}finally{generating.value=false}}
const toggle=c=>router.patch(route('cards.status',c.id));
</script>
<template><Layout><Head title="Tarjetas y lotes"/><main class="page"><header><div><small>ACTIVACIONES</small><h1>Tarjetas y lotes</h1><p>Genera códigos para impresión y controla su activación.</p></div><div><a :href="route('exports.members')">Exportar socios</a><a :href="route('exports.summary')">Exportar resumen</a></div></header><aside class="access-qr"><img v-if="accessQr" :src="accessQr" width="160" height="160" alt="QR de acceso al registro de socios"><div><h2>Acceso desde el celular</h2><p>Escanea este QR para activar una tarjeta. El socio ingresa el código impreso en su tarjeta.</p><a :href="route('membership.register')">Abrir registro de socios</a><a v-if="accessQr" :href="accessQr" download="hacienda-registro-qr.png">Descargar QR</a><p>Acceso del personal: <a :href="route('staff.redeem')">Canjear beneficios</a></p></div></aside><section class="grid"><form @submit.prevent="create"><h2>Nuevo lote</h2><label>Referencia<input v-model="f.name" required></label><label>Cantidad de tarjetas<input v-model="f.quantity" type="number" min="1" max="5000" required></label><label>Vencimiento <i>Opcional</i><input v-model="f.expires_at" type="date"></label><fieldset><legend>Contenido de cada cuponera</legend><p class="help">Indica cuántas unidades de cada beneficio recibirá el socio al activar una tarjeta de este lote. Con valor 1, cada cuponera tendrá un cupón de ese beneficio.</p><label v-for="c in coupons" :key="c.id">{{c.name}}<input v-model="f.coupon_quantities[c.id]" type="number" min="0" max="50"></label></fieldset><small class="error">{{error}}</small><button :disabled="generating">{{generating?'Generando…':'Generar y descargar códigos'}}</button></form><section><h2>Lotes</h2><article v-for="b in batches" :key="b.id"><div><b>{{b.name}}</b><span>{{b.activated_count}} activadas · {{b.available_count}} disponibles · {{b.cards_count}} total</span></div><a class="export" :href="route('card-batches.export',b.id)"><i class="ri-download-2-line"></i> Exportar códigos</a></article></section></section><section class="cards"><h2>Últimas tarjetas</h2><table><thead><tr><th>Tarjeta</th><th>Lote</th><th>Socio</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="c in cards" :key="c.id"><td>•••• {{c.activation_code_last4}}</td><td>{{c.batch?.name}}</td><td>{{c.member?.name||'Sin registrar'}}</td><td>{{c.status}}</td><td><button v-if="['available','blocked'].includes(c.status)" @click="toggle(c)">{{c.status==='blocked'?'Desbloquear':'Bloquear'}}</button></td></tr></tbody></table></section></main></Layout></template>
<style scoped>.access-qr{display:flex;gap:24px;align-items:center;background:#fff8e9;padding:22px;border:1px solid #9c8a7270;border-radius:12px;margin:24px 0}.access-qr a{display:inline-block;margin-right:18px;padding:8px 0;color:#8f3b28}.access-qr p{font-size:12px}.access-qr img{max-width:100%;height:auto}@media(max-width:600px){.access-qr{flex-direction:column;align-items:start}}.page{max-width:1300px;margin:auto;color:#332820}.page>header{display:flex;justify-content:space-between;align-items:end}.page>header small{color:#993b2a;letter-spacing:.2em}.page>header a{display:inline-block;margin-left:8px;background:#576443;color:white;padding:10px;border-radius:8px}h1,h2{font-family:Georgia}.grid{display:grid;grid-template-columns:420px 1fr;gap:20px;margin-top:25px}.grid>form,.grid>section,.cards{background:white;padding:22px;border-radius:15px}label{display:block;margin:10px 0;font-size:12px;font-weight:700}input{display:block;width:100%;padding:9px;border:1px solid #d9cdbd;border-radius:7px}fieldset{margin-top:18px;border:1px solid #e2d8c9;border-radius:10px;padding:15px}fieldset legend{font:22px Georgia;padding:0 7px}.help{color:#786f67;font-size:12px;line-height:1.5}fieldset label{display:grid;grid-template-columns:1fr 80px;align-items:center}.grid article{display:flex;justify-content:space-between;align-items:center;padding:14px;border-bottom:1px solid #eee}.grid article div{display:flex;flex-direction:column}.grid article span{color:#776}.export{border:1px solid #576443;color:#576443;padding:8px 10px;border-radius:7px;font-size:12px;white-space:nowrap}.grid form>button{width:100%;background:#993b2a;color:white;border:0;padding:12px;border-radius:8px}.error{display:block;color:#993b2a;margin:8px 0}.cards{margin-top:20px;overflow:auto}table{width:100%;border-collapse:collapse}td,th{padding:12px;text-align:left;border-top:1px solid #eee}td button{border:1px solid #993b2a;color:#993b2a;background:white;border-radius:7px;padding:6px}@media(max-width:850px){.grid{grid-template-columns:1fr}.page>header{align-items:start;flex-direction:column;gap:12px}.grid article{align-items:start;gap:10px;flex-direction:column}}</style>
