<script setup>
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue'; import {Head,useForm} from '@inertiajs/vue3';
const props=defineProps({registrationToken:String,maskedEmail:String,retryAfter:Number,expiresAt:Number});
const now=()=>Math.floor(Date.now()/1000); const remaining=ref(Math.max(0,props.expiresAt-now())); const resendWait=ref(Math.max(0,Math.ceil(props.retryAfter||0))); let timer;
const form=useForm({registration_token:props.registrationToken,code:''}); const resend=useForm({registration_token:props.registrationToken});
const expired=computed(()=>remaining.value<=0); const clock=computed(()=>`${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`);
const verify=()=>{if(!expired.value)form.post(route('membership.verify'))};
const sendAgain=()=>{if(resendWait.value>0||resend.processing)return;resend.post(route('membership.verify.resend'),{preserveScroll:true,onSuccess:()=>{remaining.value=300;resendWait.value=60;form.clearErrors();form.reset('code')}})};
watch(()=>props.expiresAt,value=>remaining.value=Math.max(0,value-now())); watch(()=>props.retryAfter,value=>resendWait.value=Math.max(0,Math.ceil(value||0)));
onMounted(()=>timer=setInterval(()=>{remaining.value=Math.max(0,props.expiresAt-now());resendWait.value=Math.max(0,resendWait.value-1)},1000)); onBeforeUnmount(()=>clearInterval(timer));
</script>
<template><Head title="Verifica tu correo"/><main class="verify-page"><div class="brand"><strong>HACIENDA</strong><b>MONTE RICO</b><small>CLUB DE SOCIOS</small></div><section><div class="icon"><i class="ri-mail-line"></i></div><span>VERIFICACIÓN</span><h1>Revisa tu correo</h1><p>Enviamos un código de 6 dígitos a <b>{{maskedEmail}}</b>.</p><div :class="['timer',{expired}]"><small>{{expired?'EL CÓDIGO VENCIÓ':'TIEMPO RESTANTE'}}</small><strong>{{clock}}</strong></div><form @submit.prevent="verify"><input v-model="form.code" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" autocomplete="one-time-code" placeholder="000000" autofocus required :disabled="expired"><small class="error">{{form.errors.code}}</small><button :disabled="form.processing||expired">{{expired?'Solicita un código nuevo':'Verificar y activar cuponera'}} <i>→</i></button></form><button class="resend" :disabled="resend.processing||resendWait>0" @click="sendAgain">{{resendWait>0?`Reenviar código en ${resendWait}s`:'Enviar un código nuevo'}}</button><small class="error">{{resend.errors.code}}</small></section><footer>Hacienda Monterrico · Desde 1906</footer></main></template>
<style scoped>.verify-page{min-height:100dvh;background:radial-gradient(circle at top,#564136 0,#332820 58%);display:flex;flex-direction:column;align-items:center;justify-content:center;padding:28px 18px;color:#332820}.brand{text-align:center;color:#fff8e9;margin-bottom:20px;line-height:.9}.brand strong,.brand b,.brand small{display:block}.brand strong{font:20px Georgia}.brand b{font:34px Georgia;color:#c8b898}.brand small{font:8px Arial;letter-spacing:.28em;margin-top:9px}.verify-page>section{width:min(460px,100%);background:#fffaf1;text-align:center;padding:34px;border-radius:24px;box-shadow:0 24px 70px #140b0788}.icon{width:62px;height:62px;border-radius:50%;display:grid;place-items:center;margin:auto;background:#eee4d2;font-size:27px}span{display:block;color:#993b2a;letter-spacing:.22em;font-size:10px;font-weight:800;margin-top:20px}h1{font:clamp(30px,8vw,40px) Georgia;margin:8px}p{color:#756b62;line-height:1.5;margin:10px auto;max-width:330px}.timer{display:flex;justify-content:center;align-items:center;gap:12px;margin:18px auto 4px;color:#576443}.timer small{font-size:9px;letter-spacing:.15em}.timer strong{font:25px Georgia}.timer.expired{color:#993b2a}input{box-sizing:border-box;display:block;width:100%;font-size:clamp(23px,7vw,32px);letter-spacing:.32em;text-align:center;padding:14px 8px;border:1px solid #d9cdbd;border-radius:10px;margin-top:18px;background:white}button{width:100%;min-height:49px;padding:13px;border:0;border-radius:9px;background:#993b2a;color:white;font-weight:800;margin-top:14px}button i{float:right}button:disabled{opacity:.55;cursor:not-allowed}.resend{background:transparent;color:#576443;border:1px solid #576443}.error{display:block;color:#993b2a;margin-top:6px}.verify-page>footer{color:#c8b898;font-size:10px;letter-spacing:.12em;margin-top:20px}@media(max-width:480px){.verify-page{justify-content:flex-start;padding:20px 12px}.brand{margin:5px 0 18px}.verify-page>section{padding:25px 18px;border-radius:20px}input{letter-spacing:.22em}.timer{margin-top:14px}}@media(max-height:700px){.verify-page{justify-content:flex-start}.brand{margin-bottom:12px}.verify-page>section{padding-top:22px;padding-bottom:22px}.icon{width:52px;height:52px}h1{margin:5px}.verify-page>footer{margin-top:12px}}</style>
